import { VisualizerScene, Finish } from '@/types/visualizer';

// ─── Finishes Catalog ─────────────────────────────────────────────────────────
export const FINISHES: Record<string, Finish[]> = {
  Plywood: [
    {
      id: 'ply-birch',
      name: 'Natural Birch Core',
      sku: 'PLY-BRCH-01',
      specLine: 'Architectural Birch Core Plywood Panel',
      category: 'Plywood',
      thumbnailImage: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 120,
      tileHeightCm: 120,
      materialType: 'wood',
      tags: ['natural', 'birch', 'light'],
    },
    {
      id: 'ply-oak',
      name: 'Smoked Crown Oak',
      sku: 'PLY-OAK-04',
      specLine: 'Premium Crown Oak Veneer Panel',
      category: 'Plywood',
      thumbnailImage: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 100,
      tileHeightCm: 100,
      materialType: 'wood',
      tags: ['dark', 'oak', 'smoked'],
    },
    {
      id: 'ply-walnut',
      name: 'American Walnut',
      sku: 'PLY-WLNT-09',
      specLine: 'American Black Walnut Plywood',
      category: 'Plywood',
      thumbnailImage: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 140,
      tileHeightCm: 140,
      materialType: 'wood',
      tags: ['dark', 'walnut', 'rich'],
    },
  ],
  Laminates: [
    {
      id: 'lam-yellow',
      name: 'Sitka Brand Yellow',
      sku: 'LAM-YEL-500',
      specLine: 'Sitka Yellow High Pressure Laminate',
      category: 'Laminates',
      thumbnailImage: '', // Will fall back to color
      tileableTexture: '', // Will use color
      color: '#F5B800',
      materialType: 'gloss',
      tags: ['yellow', 'brand', 'gloss'],
    },
    {
      id: 'lam-charcoal',
      name: 'Matte Obsidian Charcoal',
      sku: 'LAM-CHAR-12',
      specLine: 'Anti-fingerprint Matte Charcoal Laminate',
      category: 'Laminates',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#2C2825',
      materialType: 'matte',
      tags: ['charcoal', 'matte', 'dark'],
    },
    {
      id: 'lam-parchment',
      name: 'Alabaster Parchment',
      sku: 'LAM-PARCH-88',
      specLine: 'Soft Alabaster Parchment Laminate',
      category: 'Laminates',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#EDE6D8',
      materialType: 'satin',
      tags: ['white', 'parchment', 'light'],
    },
    {
      id: 'lam-sage',
      name: 'Nordic Sage Green',
      sku: 'LAM-SAGE-21',
      specLine: 'Muted Nordic Sage Green Laminate',
      category: 'Laminates',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#7A8F7A',
      materialType: 'matte',
      tags: ['green', 'sage', 'matte'],
    },
    {
      id: 'lam-terracotta',
      name: 'Fired Terracotta',
      sku: 'LAM-TERRA-07',
      specLine: 'Fired Earth Terracotta Laminate',
      category: 'Laminates',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#B5603A',
      materialType: 'satin',
      tags: ['terracotta', 'warm'],
    },
    {
      id: 'lam-slate',
      name: 'Storm Grey Slate',
      sku: 'LAM-SLATE-33',
      specLine: 'Engineered Storm Grey Slate Laminate',
      category: 'Laminates',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#5C6370',
      materialType: 'matte',
      tags: ['grey', 'slate'],
    },
  ],
  Veneer: [
    {
      id: 'ven-teak',
      name: 'Burmese Golden Teak',
      sku: 'VEN-TEAK-33',
      specLine: 'Natural Golden Teak Veneer Sheet',
      category: 'Veneer',
      thumbnailImage: 'https://images.unsplash.com/photo-1601058268499-e52658b8bb88?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1601058268499-e52658b8bb88?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 110,
      tileHeightCm: 110,
      materialType: 'wood',
      tags: ['wood', 'teak', 'golden'],
    },
    {
      id: 'ven-ash',
      name: 'Parchment White Ash',
      sku: 'VEN-ASH-15',
      specLine: 'Lacquered White Ash Veneer',
      category: 'Veneer',
      thumbnailImage: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 80,
      tileHeightCm: 80,
      materialType: 'wood',
      tags: ['wood', 'ash', 'light'],
    },
    {
      id: 'ven-maple',
      name: 'Figured Maple',
      sku: 'VEN-MPL-08',
      specLine: 'Lacquered Figured Maple Veneer',
      category: 'Veneer',
      thumbnailImage: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 100,
      tileHeightCm: 100,
      materialType: 'wood',
      tags: ['wood', 'maple', 'light'],
    },
  ],
  Decoratives: [
    {
      id: 'dec-slat',
      name: 'Oak Acoustic Slat',
      sku: 'DEC-SLAT-02',
      specLine: 'Sound-Dampening Oak Acoustic Slat Panel',
      category: 'Decoratives',
      thumbnailImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=256&auto=format&fit=crop',
      tileableTexture: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=1024&auto=format&fit=crop',
      tileWidthCm: 120,
      tileHeightCm: 120,
      materialType: 'stone',
      tags: ['decorative', 'acoustic', 'slat'],
    },
    {
      id: 'dec-concrete',
      name: 'Raw Concrete Panel',
      sku: 'DEC-CONC-05',
      specLine: 'Architectural Textured Raw Concrete Panel',
      category: 'Decoratives',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#9E9E9E',
      materialType: 'stone',
      tags: ['concrete', 'industrial', 'grey'],
    },
    {
      id: 'dec-brass',
      name: 'Polished Brass Trim',
      sku: 'DEC-BRSS-07',
      specLine: 'Polished Metallic Brass Finish Trim',
      category: 'Decoratives',
      thumbnailImage: '',
      tileableTexture: '',
      color: '#D4A017',
      materialType: 'gloss',
      tags: ['brass', 'gold', 'metallic'],
    },
  ],
};

// Flatten to list of allowed finishes for defaults
const allFinishes = Object.values(FINISHES).flat();

// ─── Default Mock Scene Setup ────────────────────────────────────────────────
export const defaultScene: VisualizerScene = {
  id: 'kitchen-main-scene',
  name: 'Modern Kitchen Visualiser',
  slug: 'kitchen-main-scene',
  roomImage: '/visualizer-room.png',
  naturalWidth: 1024,
  naturalHeight: 1024,
  status: 'PUBLISHED',
  displayOrder: 0,
  whereShown: ['HOMEPAGE', 'VISUALIZER'],
  overlaySettings: {
    opacity: 0.75,
  },
  zones: [
    {
      id: 'wall',
      label: 'Feature Wall',
      mask: null,
      shadingLayer: null,
      corners: [
        [0, 0],       // TL
        [1024, 0],     // TR
        [1024, 317],   // BR
        [0, 317],      // BL
      ],
      widthCm: 360,
      heightCm: 120,
      allowedCategories: ['Plywood', 'Laminates', 'Veneer', 'Decoratives'],
      defaultFinish: FINISHES.Plywood[2], // American Walnut
      displayOrder: 1,
    },
    {
      id: 'upperCabinet',
      label: 'Upper Cabinets',
      mask: null,
      shadingLayer: null,
      corners: [
        [0, 317],
        [1024, 317],
        [1024, 481],
        [0, 481],
      ],
      widthCm: 360,
      heightCm: 50,
      allowedCategories: ['Plywood', 'Laminates', 'Veneer'],
      defaultFinish: FINISHES.Veneer[0], // Burmese Teak
      displayOrder: 2,
    },
    {
      id: 'countertop',
      label: 'Countertop',
      mask: null,
      shadingLayer: null,
      corners: [
        [0, 481],
        [1024, 481],
        [1024, 614],
        [0, 614],
      ],
      widthCm: 360,
      heightCm: 50,
      allowedCategories: ['Laminates', 'Decoratives'],
      defaultFinish: FINISHES.Laminates[5], // Slate
      displayOrder: 3,
    },
    {
      id: 'lowerCabinet',
      label: 'Lower Cabinets',
      mask: null,
      shadingLayer: null,
      corners: [
        [0, 614],
        [1024, 614],
        [1024, 901],
        [0, 901],
      ],
      widthCm: 360,
      heightCm: 90,
      allowedCategories: ['Laminates', 'Plywood'],
      defaultFinish: FINISHES.Laminates[1], // Charcoal
      displayOrder: 4,
    },
    {
      id: 'floor',
      label: 'Floor',
      mask: null,
      shadingLayer: null,
      corners: [
        [0, 901],
        [1024, 901],
        [1024, 1024],
        [0, 1024],
      ],
      widthCm: 360,
      heightCm: 40,
      allowedCategories: ['Veneer', 'Plywood'],
      defaultFinish: FINISHES.Veneer[2], // Figured Maple
      displayOrder: 5,
    },
  ],
};
